---
title: "p8105_hw2_pika1218"
author: "pika"
date: "2/23/2022"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
```

## Problem 1
```{r}
Trash_wheel_df=
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = "Mr. Trash Wheel", range = ("A2:N408")) %>% 
  janitor::clean_names() %>% 
  select(-dumpster) %>% 
  mutate(sports_balls = round(sports_balls)) 
  

```

```{r}
Precipitation_2018_df=
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = "2018 Precipitation", range = ("A2:B15")) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018)

Precipitation_2019_df=
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = "2019 Precipitation", skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year = 2019)

combine_df= 
  bind_rows(Precipitation_2018_df, Precipitation_2019_df) %>% 
  mutate(month = month.name[as.numeric(month)])
  
```


## Problem 2

```{r}
pol_month_df=
  read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
  separate(mon, into = c ("year", "month", "day"), convert = TRUE) %>% 
  mutate(month = month.name[as.numeric(month)]) %>% 
  mutate(president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) %>% 
  select(-prez_dem, -prez_gop, -day)
  

pol_month_df %>% 
  group_by(president) %>% 
  summarize(
    n_obs = n()
  )



```


```{r}
snp_df=
  read.csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
  mutate(date = mdy(date)) %>% 
  separate(date, into = c ("year", "month", "day"), convert = TRUE) %>% 
  arrange(year, month) %>% 
  mutate(month = month.name[as.numeric(month)])
  
```


```{r}
unemployment_df=
  read.csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  gather(key = month, value = unemployment_df, Jan:Dec) %>% 
  mutate(month = recode(month, "Jan" = "January", "Feb" = "February" , "Mar" = "March", "Apr" = "April", "May" = "May", "Jun" = "June", "Jul" = "July", "Aug" = "Auguest", "Sep" = "September", "Oct" = "October", "Nov" = "November", "Dec" = "December"))
```

```{r}
merging_df1=
  left_join(pol_month_df, snp_df) 

merging_df2=  
left_join(merging_df1, unemployment_df)

str(merging_df2)
```


##Problem 3

```{r}
babynames =
  read.csv("./data/Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    childs_first_name = str_to_sentence(child_s_first_name),
    ethnicity = str_to_sentence(ethnicity)
    ) %>% 
  select(-child_s_first_name) %>% 
  mutate(
    ethnicity = recode(ethnicity, "Asian and paci" = "Asian and pacific islander", "Black non hisp" = "Black non hispanic" , "White non hisp" = "White non hispanic")
    )








```

